# Use an official Ubuntu base image
FROM ubuntu:latest

# Set the command to run when the container starts
# This command will print the desired message to standard output
CMD ["echo", "Hello, World! This is my_container running."]
